[package]
name = "paralegal-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "4.5.0"
paralegal-policy = { path = "../../paralegal/crates/paralegal-policy" }
paralegal = { path = "../../paralegal/crates/paralegal" }
parsers = { path = "../parsers" }
templates = { path = "../templates" }
clap = { version = "3", features = ["derive"] }
